version: '3'
services:
  storybook:
    
    ports:
      - "6006:6006"
    build:
      context: ./
      dockerfile: Dockerfile
    working_dir: /usr/src/app
    restart: unless-stopped
    container_name: storybook
    volumes:
      - '.:/usr/src/app'
      - /usr/src/app/node_modules